### ISSUE TITLE
MLPerf™ Tiny Deep Learning Benchmark Models

### ISSUE THREAD

**Issue by fpedd** [tum-ei-eda/mlonmcu-models#2]
I am trying to figure out which models here belong to the official [MLPerf™ Tiny Deep Learning Benchmark Models](https://github.com/mlcommons/tiny).

I am looking for the following:
- Keyword Spotting	-> ??
- Visual Wake Words -> here `vww/`
- Image Classification -> here `resnet/` 
- Anomaly Detection -> here `toycar/`

I used the `md5sum` to check for equivalency.

**Comment by PhilippvK** [comment]
@fabianpedd 

AWW = **A**udio **W**ake **W**ords -> Speech recognition/KWS.

**Comment by fpedd** [comment]
Our aww TFLite model has a different md5sum than the one from the [MLPerf™ Tiny Deep Learning Benchmark Models](https://github.com/mlcommons/tiny) repo.

[Ours](https://github.com/tum-ei-eda/mlonmcu-models/blob/main/aww/aww.tflite) -> `36a43c3b21435983885f5e64bfec9c45  aww.tflite`  
[Theirs](https://github.com/mlcommons/tiny/blob/master/benchmark/training/keyword_spotting/trained_models/kws_ref_model.tflite)   ->  `618aeb155673dae92fa6a7f26608add5  kws_ref_model.tflite`  

Their model (md5 hash) did also not change from 0.5 to 0.7.

**Comment by fpedd** [comment]
I admit that their architecture is identical (by visual inspection using netron).

**Comment by PhilippvK** [comment]
Hmm, no idea how that happened.

Then let's replace the model in this repo by the original one and update the inout data?

Have you checked if there are difference between the `v0.5` and `v0.7` versions of the benchmark models?
